spring.application.name=mvp-clientes

spring.datasource.url=jdbc:postgresql://dpg-d8r8f2mrnols73f3bh2g-a.oregon-postgres.render.com:5432/mvp_clientes_db?sslmode=require

spring.datasource.username=mvp_clientes_db_user

spring.datasource.password=8ilrKJIipNRWVTinuKjuNCWgRPMlA1GR

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true